### PR TITLE
SSLSocket write and non-block fixes

### LINKED ISSUE #242: gem push fails with Broken Pipe IOError
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc): `9.3.0.0`
* Operating system and platform (e.g. `uname -a`): `Darwin Andys-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

Other relevant info you may wish to add:
* `gem --version` returns 3.2.28

**Expected Behavior**

Running `gem push path_to_gem.gem` should result in releasing the gem to RubyGems.org successfully.

This works in `jruby-9.2.19.0`

**Actual Behavior**

In `jruby-9.3.0.0`, I get a broken pipe IOError when running `gem push path_to_gem.gem`:

```
% gem push pkg/glimmer-dsl-swt-4.21.0.1.gem 
Pushing gem to https://rubygems.org...
ERROR:  While executing gem ... (IOError)
    Broken pipe
```

It works fine in `ruby-3.0.2` and `jruby-9.2.19.0`. My Internet works well and the same in all cases.

### LINKED ISSUE #271: OpenSSL::Buffering#read_nonblock(..., exception: false) can still throw exceptions
Hello. I am not sure whether it's a jruby-openssl's or jruby's bug, but opening the issue here for now. Also, I don't have a way to reproduce, but it does reproduce with jruby-openssl 0.12.2 and 0.14.0 on jruby 9.2.21.0 and 9.3.9.0.

We're using httprb library, which has the following code (https://github.com/httprb/http/blob/main/lib/http/timeout/per_operation.rb#L41):
```
result = @socket.read_nonblock(size, buffer, :exception => false)
```

Which in my case leads to OpenSSL::Buffering#read_nonblock method. As you can see, it asks the method not to return the exception, but sometimes we get an exception from this method with class "OpenSSL::SSL::SSLErrorWaitReadable" and message "read would block" with this backtrace:

```
org/jruby/ext/openssl/SSLSocket.java:883:in `sysread_nonblock'
/opt/jruby/lib/ruby/stdlib/openssl/buffering.rb:205:in `read_nonblock'
/usr/local/bundle/gems/http-4.4.1/lib/http/timeout/per_operation.rb:63:in `block in readpartial'
org/jruby/RubyKernel.java:1442:in `loop'
/usr/local/bundle/gems/http-4.4.1/lib/http/timeout/per_operation.rb:62:in `readpartial'
```

As I said - I don't have neither a minimal code that reproduces the bug, nor an understanding on when it happens. For us it happened when we tried to connect to AWS-managed kubernetes apiserver (which means I can't get any info about what is happening there), but I assume that it should be pretty easy to understand where the problem lies for the person familiar with jruby-openssl and jruby itself.

cc @headius

### PR DESCRIPTION
**Pull request by kares**
another attempt at (*minimal*) fixing non-blocking write + read.

similar to #351 but wout test madness (tests here are still not great but we can revisit those later)

includes https://github.com/jruby/jruby-openssl/pull/347

### CODE REVIEW

File: src/main/java/org/jruby/ext/openssl/SSLSocket.java [hunk 1]
```diff
@@ -614,7 +611,7 @@ private IRubyObject doHandshake(final boolean blocking, final boolean exception)
 
     private void doWrap(final boolean blocking) throws IOException {
         netWriteData.clear();
-        SSLEngineResult result = engine.wrap(dummy, netWriteData);
+        SSLEngineResult result = engine.wrap(EMPTY_DATA.duplicate(), netWriteData);
```
Comment (headius) [inline src/main/java/org/jruby/ext/openssl/SSLSocket.java:614]: Is it necessary to duplicate EMPTY_DATA? It is already zero-length and marked as read-only.

File: src/main/java/org/jruby/ext/openssl/SSLSocket.java [hunk 2]
```diff
@@ -793,7 +795,7 @@ private void doShutdown() throws IOException {
         }
         netWriteData.clear();
         try {
-            engine.wrap(dummy, netWriteData); // send close (after sslEngine.closeOutbound)
+            engine.wrap(EMPTY_DATA.duplicate(), netWriteData); // send close (after sslEngine.closeOutbound)
```
Comment (headius) [inline src/main/java/org/jruby/ext/openssl/SSLSocket.java:798]: Ditto here, why duplicate?

**Comment by kares** [comment]
@jsvd have included #347 here, if you have any opinions please share

File: src/test/java/org/jruby/ext/openssl/SSLSocketTest.java [hunk 3]
```diff
@@ -0,0 +1,251 @@
...
+            RubyString payload = RubyString.newString(runtime, chunk);
+
+            long totalSent = 0;
+            for (int i = 0; i < 64; i++) { // 64 * 4KB = 256KB
+                try {
+                    IRubyObject written = client.syswrite_nonblock(currentContext(), payload);
+                    totalSent += ((RubyInteger) written).getLongValue();
+                } catch (RaiseException e) {
+                    if ("OpenSSL::SSL::SSLErrorWaitWritable".equals(e.getException().getMetaClass().getName())) {
+                        System.out.println("syswrite_nonblock expected: " + e.getMessage());
```
Comment (headius) [inline src/test/java/org/jruby/ext/openssl/SSLSocketTest.java:77]: Shouldn't these be asserts or fails, so they show up as the cause of failure? stdout printlns can get lost in test harnesses.

File: src/test/java/org/jruby/ext/openssl/SSLSocketTest.java [hunk 4]
```diff
@@ -0,0 +1,251 @@
...
+            try {
+                RubyFixnum len = RubyFixnum.newFixnum(runtime, 8192);
+                while (true) {
+                    IRubyObject data = server.sysread(currentContext(), len);
+                    serverReceived[0] += ((RubyString) data).getByteList().getRealSize();
+                }
+            } catch (RaiseException e) {
+                String errorName = e.getException().getMetaClass().getName();
+                if ("EOFError".equals(errorName) || "IOError".equals(errorName)) { // client closes connection
+                    System.out.println("server-reader expected: " + e.getMessage());
```
Comment (headius) [inline src/test/java/org/jruby/ext/openssl/SSLSocketTest.java:113]: Again seems weird to have printlns in a test, even if it's running in a separate thread.

File: src/test/java/org/jruby/ext/openssl/SSLSocketTest.java [hunk 5]
```diff
@@ -0,0 +1,251 @@
...
+                } else {
+                    System.err.println("server-reader unexpected: " + e.getMessage());
```
Comment (headius) [inline src/test/java/org/jruby/ext/openssl/SSLSocketTest.java:115]: Now we're outputting to err?

**Review by headius — COMMENTED** [review]
The batch of fixes looks pretty good after a first review pass. The tests are heinous but you know that. I suppose in the interest of getting fixes landed we can go with them for now but they shouldn't stay like this for long. It's very hard to follow what they're testing, or if they're actually testing what they should be.

File: src/main/java/org/jruby/ext/openssl/SSLSocket.java (hunk 1 above)
Comment (kares) [reply src/main/java/org/jruby/ext/openssl/SSLSocket.java:614]: shouldn't be, except `engine.wrap` in theory does set `limit` although likely not on an empty buffer.

File: src/test/java/org/jruby/ext/openssl/SSLSocketTest.java (hunk 3 above)
Comment (kares) [reply src/test/java/org/jruby/ext/openssl/SSLSocketTest.java:77]: this part is mostly `debug` messages, the other branch fails.

they're useful esp. since a lot of time these exceptions do not have a trace.
